### ISSUE TITLE
Integrate "_subfind.sh" into subzuf itself and run by default

### ISSUE THREAD

**Issue by aels** [elceef/subzuf#2]
Since `_subfind.sh` is used all the time, why not to integrate it into **subzuf**? It will speed up entire process, bringing beautifull go async http.

**Comment by elceef** [comment]
This is subdomain fuzzer designed in a way to be flexible and chain with other tools easily. That said, you can combine different input sources, not limit yourself just to `_subfind.sh` script. Other than that, since `_subfind.sh` collects data from a number of publicly available services in parallel, I don't see any significant speed benefits from integrating it into the tool itself.
